generator_settings:
  dataset: compas
  input_attrs: ['Person_ID', 'AssessmentID', 'Case_ID', 'Agency_Text', 'LastName', 'FirstName', 'MiddleName',
                        'Sex_Code_Text', 'Ethnic_Code_Text', 'DateOfBirth', 'ScaleSet_ID', 'ScaleSet', 'AssessmentReason',
                        'Language', 'LegalStatus', 'CustodyStatus', 'MaritalStatus', 'Screening_Date',
                        'RecSupervisionLevel', 'RecSupervisionLevelText', 'Scale_ID']
  output_attrs: ['DisplayText', 'RawScore', 'DecileScore', 'ScoreText', 'AssessmentType', 'IsCompleted', 'IsDeleted']
  sensitive_attrs: ["Sex_Code_Text", "Ethnic_Code_Text"]
  evaluation_attr: "ScoreText"
  fail_vals: ["High", "Medium", "nan"]
  schema_file: ../datasets/schemas/schema_compas.yml
  data_file: ../datasets/original/COMPAS/compas-scores-raw.csv
  index_column_included: false
  delimiter: ','

output_settings:
  output_csv: ../datasets/generated/compas.csv

log:
  primary_logger_type: console
  log_level: debug
  verbosity: 0