generator_settings:
  dataset: compas
  input_attrs: ['Person_ID', 'AssessmentID', 'Case_ID', 'Agency_Text', 'LastName', 'FirstName', 'MiddleName',
                        'Sex_Code_Text', 'Ethnic_Code_Text', 'DateOfBirth', 'ScaleSet_ID', 'ScaleSet', 'AssessmentReason',
                        'Language', 'LegalStatus', 'CustodyStatus', 'MaritalStatus', 'Screening_Date',
                        'RecSupervisionLevel', 'RecSupervisionLevelText', 'Scale_ID']
  output_attrs: ['DisplayText', 'RawScore', 'DecileScore', 'ScoreText', 'AssessmentType', 'IsCompleted', 'IsDeleted']
  sut_name: Compas
  sut_path: suts/COMPAS/compas_sut.py
  oracle_name: GroupFairnessOracle
  oracle_path: oracles/group_fairness_oracle.py
  schema_file: ../datasets/schemas/schema_compas.yml
  data_file: ../datasets/original/COMPAS/compas-scores-preprocessed.csv
  index_column_included: false
  delimiter: ','

output_settings:
  output_csv: ../datasets/generated/compas.csv

log:
  primary_logger_type: console
  log_level: debug
  verbosity: 0